apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  name: fission-cron-test-second
  namespace: default
  annotations:
    fission-name: fission-cron-test
    fission-uid: 6f3da4ab-5f79-4497-ab11-a4bc5ce3a607
spec:
  cron: '@every 1s'
  functionref:
    name: fission-cron-test
    type: name
